targets:
  $default:
    sources:
      - lib/**
      - api/**
      - swagger_examples/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'api/'
          output_folder: 'lib/generated_code/'
          include_if_null:
            enabled: true
            value: false