name: brn_mobile
description: A BrainUp Mobile application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #  bloc: ^6.1.0
  flutter_bloc: ^6.1.0
  provider: ^4.3.2+4
  font_awesome_flutter: ^8.4.0
  google_fonts: ^1.1.0
  meta: ^1.1.8
  pedantic: ^1.9.0
  auto_size_text: ^2.1.0
  formz: ^0.3.1
  equatable: ^1.2.5

  chopper: ^3.0.3
  build_runner: ^1.11.1

  splashscreen: ^1.3.5
  flare_flutter: ^2.0.1

  carousel_slider: ^3.0.0
  sizer: ^1.1.8
  cupertino_icons: ^0.1.2

  integration_test: ^1.0.2+2

  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  swagger:
    path: packages/api_repository
dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.1.1
  chopper_generator: ^3.0.5
  json_annotation: ^3.0.1
  json_serializable: ^3.4.1
  swagger_dart_code_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/loading.flr
    - assets/images/Ellipse76.png
    - assets/images/Coolkidsstayinghome1.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          style: normal

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
